export const stages = [
  "New Lead",
  "In Progress",
  "Likely / Warm",
  "On Hold",
  "Converted",
  "Unspecified",
  "Not Interested",
];

export const leads = [
  {
    id: 1,
    name: "Ramesh Chaudhary",
    schoolName: "Texas Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Make the first discovery call",
    stage: "New Lead",
  },
  {
    id: 2,
    name: "Raj Chaudhary",
    schoolName: "Peace Point School",
    status: "Low",
    complexity: "HIGH",
    slogan: "Make the first discovery call",
    stage: "New Lead",
  },
  {
    id: 3,
    name: "Ramesh Chaudhary",
    schoolName: "Himanchal Boarding School",
    status: "Low",
    complexity: "NORMAL",
    slogan: "Make the first discovery call",
    stage: "New Lead",
  },
  {
    id: 4,
    name: "Preeti Bachhar",
    schoolName: "Daffodil School",
    status: "Developing",
    complexity: "HIGH",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "In Progress",
  },
  {
    id: 5,
    name: "Ramesh Chaudhary",
    schoolName: "Satyavadi Secondary School/Bajhang",
    status: "Low",
    complexity: "HIGH",
    slogan: "Make the first discovery call",
    stage: "In Progress",
  },
  {
    id: 6,
    name: "Preeti Bachhar",
    schoolName: "Kundalinee School",
    status: "Warm",
    complexity: "MEDIUM",
    slogan: "Send a tailored proposal and decision timeline",
    stage: "In Progress",
  },
  {
    id: 7,
    name: "Ramesh Chaudhary",
    schoolName: "St. Xaviers School, Jwalakhel",
    status: "Developing",
    complexity: "MEDIUM",
    slogan: "Complete the scheduled follow up today",
    stage: "Likely / Warm",
  },
  {
    id: 8,
    name: "Preeti Bachhar",
    schoolName: "Living Stone Academy",
    status: "Warm",
    complexity: "HIGH",
    slogan: "Complete the scheduled follow up today",
    stage: "Likely / Warm",
  },
  {
    id: 9,
    name: "Ramesh Chaudhary",
    schoolName: "Life Skills Pre School",
    status: "Developing",
    complexity: "HIGH",
    slogan: "Complete the scheduled follow up today",
    stage: "Likely / Warm",
  },
  {
    id: 10,
    name: "Ramesh Chaudhary",
    schoolName: "ISBS",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "On Hold",
  },
  {
    id: 11,
    name: "Ramesh Chaudhary",
    schoolName: "New Supersence Public Academy",
    status: "Low",
    complexity: "LOW",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "On Hold",
  },
  {
    id: 12,
    name: "Ramesh Chaudhary",
    schoolName: "Hamro Shishu Syahar Bikas Kendra PL",
    status: "Developing",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "On Hold",
  },
  {
    id: 13,
    name: "Ramesh Chaudhary",
    schoolName: "GEMS School",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Converted",
  },
  {
    id: 14,
    name: "Ramesh Chaudhary",
    schoolName: "Little Angels School",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Converted",
  },
  {
    id: 15,
    name: "Ramesh Chaudhary",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Converted",
  },

  {
    id: 16,
    name: "Ramesh Chaudhary",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Unspecified",
  },
  {
    id: 17,
    name: "Ramesh Chaudhary",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Unspecified",
  },
  {
    id: 18,
    name: "Preeti Bachhar",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Unspecified",
  },
  {
    id: 19,
    name: "Renuka Shrestha",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Not Interested",
  },
  {
    id: 20,
    name: "Ramesh Chaudhary",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Not Interested",
  },
  {
    id: 21,
    name: "Renuka Shrestaha",
    schoolName: "Rose Academy",
    status: "Low",
    complexity: "MEDIUM",
    slogan: "Re-engage with a short call or WhatsApp message",
    stage: "Not Interested",
  },
];
